# Generated by Django 4.1.4 on 2022-12-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fruits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderround",
            name="fruit_id",
        ),
    ]
