# Generated by Django 4.1.4 on 2022-12-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fruits", "0002_remove_orderround_fruit_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_entries",
        ),
        migrations.RemoveField(
            model_name="round",
            name="round_entries",
        ),
    ]
