# Generated by Django 4.1.4 on 2022-12-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fruits", "0003_remove_order_order_entries_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_entries",
            field=models.ManyToManyField(
                default=None,
                related_name="order_entries",
                through="fruits.OrderEntry",
                to="fruits.fruit",
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="round_entries",
            field=models.ManyToManyField(
                related_name="round_entries",
                through="fruits.RoundEntry",
                to="fruits.fruit",
            ),
        ),
    ]
