# Generated by Django 4.1.4 on 2022-12-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fruits", "0004_order_order_entries_round_round_entries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_entries",
        ),
    ]
