# Generated by Django 4.1.4 on 2022-12-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fruits", "0005_remove_order_order_entries"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_entries",
            field=models.ManyToManyField(
                default=None, through="fruits.OrderEntry", to="fruits.fruit"
            ),
        ),
    ]
