# Generated by Django 4.1.4 on 2022-12-13 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fruits", "0006_order_order_entries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_entries",
        ),
        migrations.AddField(
            model_name="order",
            name="entries",
            field=models.ManyToManyField(
                default=None,
                related_name="order_entries",
                through="fruits.OrderEntry",
                to="fruits.fruit",
            ),
        ),
        migrations.AlterField(
            model_name="orderentry",
            name="order_id",
            field=models.ForeignKey(
                db_column="order_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_entries",
                to="fruits.order",
            ),
        ),
    ]
