# Generated by Django 4.1.4 on 2022-12-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fruits", "0008_rename_round_entries_round_entries_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="entries",
            field=models.ManyToManyField(
                default=None, through="fruits.OrderEntry", to="fruits.fruit"
            ),
        ),
    ]
