# Generated by Django 4.1.4 on 2022-12-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fruits", "0009_alter_order_entries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="entries",
            field=models.ManyToManyField(
                default=None,
                related_name="order_entries",
                through="fruits.OrderEntry",
                to="fruits.fruit",
            ),
        ),
    ]
