# Generated by Django 4.1.4 on 2022-12-13 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fruits", "0010_alter_order_entries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="entries",
        ),
    ]
